name:                defx
version:             0.0.2.0
github:              "telostat/defx"
license:             BSD3
author:              "Vehbi Sinan Tunalioglu"
maintainer:          "vst@vsthost.com"
copyright:           "2017-2021 Telostat Pte Ltd"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/telostat/defx#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- http-client
- http-conduit
- http-types
- mtl
- path
- path-io
- safe-decimal
- scientific
- text
- time
- unordered-containers
- yaml

library:
  source-dirs: src
  default-extensions:
  ## GHC 2021 extensions (see https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0380-ghc2021.rst):
  - ConstraintKinds
  - DeriveGeneric
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  ## Project specific:
  - OverloadedStrings


executables:
  defx-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - defx
    - optparse-applicative

tests:
  defx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - defx

  defx-doctest:
    main:                doctest.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    dependencies:
    - defx
    - doctest
